### ISSUE TITLE
phidget21h not found

### ISSUE THREAD

**Issue by Russ76** [dusty-nv/turbo2#3]

**Comment by Russ76** [comment]
I see now, this is a gyroscope unit. No, I don't have this, nor GPS. What I want my Rover to do is first I'll guide her on a path through the yard, then I want to transfer control to her and have her duplicate the trek. She'll need to use landmarks to learn position and the yard. She doesn't have servos, just motors. The ZED should be accurate enough to make up for the lack of encoders. Or am I dreaming?

**Comment by Russ76** [comment]
ubuntu@tegra-ubuntu:~/turbo2/build$ make
Scanning dependencies of target turbo2
[  6%] Building CXX object CMakeFiles/turbo2.dir/evdevController.cpp.o
[ 13%] Building CXX object CMakeFiles/turbo2.dir/main.cpp.o
[ 20%] Building CXX object CMakeFiles/turbo2.dir/MotorController.cpp.o
[ 26%] Building CXX object CMakeFiles/turbo2.dir/phidgetIMU.cpp.o
/home/ubuntu/turbo2/phidgetIMU.cpp:7:23: fatal error: phidget21.h: No such file or directory
 #include <phidget21.h>
                       ^
compilation terminated.
make[2]: **\* [CMakeFiles/turbo2.dir/phidgetIMU.cpp.o] Error 1
make[1]: **\* [CMakeFiles/turbo2.dir/all] Error 2
make: **\* [all] Error 2
ubuntu@tegra-ubuntu:~/turbo2/build$ 

Dusty: This is what it shows in Terminal. I don't find that file anywhere, "phidget21.h"

Russ

**Comment by dusty-nv** [comment]
Here's the link to the phidget SDK source:   [http://www.phidgets.com/downloads/libraries/libphidget.tar.gz](url)
Here are the directions for installing it:  [http://www.phidgets.com/docs/OS_-_Linux#Installing](url)
I need to add an #ifdef into the CMakeLists to automatically detect if it's installed or not.
Do you have an IMU?   What are you using?

**Comment by Russ76** [comment]
Dusty: I don't have an IMU yet but should incorporate one. Now I'm waiting on an Orbitty board from ConnectTech to replace the NVIDIA development board, that has a bad USB 3.0 port. They say May 30 ship date.

**Comment by Russ76** [comment]
Would it be possible to load most of ROS on the SD card in order to keep more memory free in the main TX1 MMC?

**Comment by dusty-nv** [comment]
Orbitty, cool.

> Would it be possible to load most of ROS on the SD card in order to keep more memory free in the main TX1 MMC?

I know ROS installs many packages, but maybe it's possible to tweak the install script to SD card?  
Had to do a similar thing for [Deep Visualization Toolbox](https://github.com/yosinski/deep-visualization-toolbox).  Also, [rovernet](https://github.com/dusty-nv/rovernet) installs everything to a local sandbox directory, making it easy to install on external media.
